### PR TITLE
Added records, multiline strings and rewrote parser in FParsec

### PR DESCRIPTION
**Pull request by schwarzeszeux**
I'm opening this PR in order to have a discussion about any changes you might want to see.
This is in response to #18 

I've left some debug-code inside the parser and haven't cleaned up parser code yet.

- Migrated test-project to .net6.0
- Added multiline literals (triple qouted string)
- Replaced most of regex-Parsing code with a FParsec-version
- Added support for records

### CODE REVIEW

**Comment by Dzoukr** [comment]
Looks great, I think you can just continue until you'd call it finished (with green tests of course 😁). Then we can merge it and create a new (rather major?) version.

**Comment by schwarzeszeux** [comment]
I merged a branch by accident - I've removed the code from this PR and now all tests should be green again :)

I've also removed all the debug code and code that's not needed anymore.
In other words, it's ready to be merged from my point of view.

**Comment by Dzoukr** [comment]
Sooooo, can we make this a new version then? 😄

**Comment by schwarzeszeux** [comment]
That's up to you ;)

You have my go for what it's worth :)

**Comment by Dzoukr** [comment]
Thanks for all the work - now published as v2.0.0! 🎊

**Comment by Dzoukr** [comment]
Thanks for all the work - now published as v2.0.0! 🎊

**Pull request merged**
